// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gctnlvogurrywjznatwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjdG5sdm9ndXJyeXdqem5hdHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDIxMzUsImV4cCI6MjA1NzcxODEzNX0.hAPxcKlYl0DEmFVTdwqecmTN-DIzlWRBHBVgPk6F0f0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);